CREATE TABLE driver
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_id         INTEGER                                  NOT NULL,
    first_name      VARCHAR(255)                             NOT NULL,
    last_name       VARCHAR(255)                             NOT NULL,
    profile_picture VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_driver PRIMARY KEY (id)
);

CREATE TABLE fantasy_race_point
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    race_id   INTEGER                                 NOT NULL,
    driver_id INTEGER,
    team_id   INTEGER,
    point     INTEGER                                 NOT NULL,
    CONSTRAINT pk_fantasy_race_point PRIMARY KEY (id)
);

CREATE TABLE grand_prix
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label    VARCHAR(255)                             NOT NULL,
    start_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    end_at   TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_grand_prix PRIMARY KEY (id)
);

CREATE TABLE race
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grand_prix_id INTEGER                                  NOT NULL,
    label         VARCHAR(255)                             NOT NULL,
    start_at      TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    type          SMALLINT                                 NOT NULL,
    CONSTRAINT pk_race PRIMARY KEY (id)
);

CREATE TABLE race_result
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    driver_id INTEGER                                 NOT NULL,
    race_id   INTEGER                                 NOT NULL,
    position  INTEGER                                 NOT NULL,
    dnf       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_race_result PRIMARY KEY (id)
);

CREATE TABLE team
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label VARCHAR(255)                             NOT NULL,
    logo  VARCHAR(255),
    CONSTRAINT pk_team PRIMARY KEY (id)
);

CREATE TABLE user_team
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID                                    NOT NULL,
    label   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user_team PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         UUID         NOT NULL,
    username   VARCHAR(255) NOT NULL,
    enabled    BOOLEAN      NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE team
    ADD CONSTRAINT uc_team_label UNIQUE (label);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE driver
    ADD CONSTRAINT FK_DRIVER_ON_TEAM FOREIGN KEY (team_id) REFERENCES team (id);

ALTER TABLE fantasy_race_point
    ADD CONSTRAINT FK_FANTASY_RACE_POINT_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES driver (id);

ALTER TABLE fantasy_race_point
    ADD CONSTRAINT FK_FANTASY_RACE_POINT_ON_RACE FOREIGN KEY (race_id) REFERENCES race (id);

ALTER TABLE fantasy_race_point
    ADD CONSTRAINT FK_FANTASY_RACE_POINT_ON_TEAM FOREIGN KEY (team_id) REFERENCES team (id);

ALTER TABLE race
    ADD CONSTRAINT FK_RACE_ON_GRAND_PRIX FOREIGN KEY (grand_prix_id) REFERENCES grand_prix (id);

ALTER TABLE race_result
    ADD CONSTRAINT FK_RACE_RESULT_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES driver (id);

ALTER TABLE race_result
    ADD CONSTRAINT FK_RACE_RESULT_ON_RACE FOREIGN KEY (race_id) REFERENCES race (id);

ALTER TABLE user_team
    ADD CONSTRAINT FK_USER_TEAM_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);