CREATE TABLE app_user
(
    id         UUID                 NOT NULL,
    username   VARCHAR(255)         NOT NULL,
    enabled    BOOLEAN DEFAULT TRUE NOT NULL,
    password   VARCHAR(255)         NOT NULL,
    role       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE constructor
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                             NOT NULL,
    logo      VARCHAR(255),
    full_logo VARCHAR(255),
    CONSTRAINT pk_constructor PRIMARY KEY (id)
);

CREATE TABLE driver
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(255)                             NOT NULL,
    last_name       VARCHAR(255)                             NOT NULL,
    profile_picture VARCHAR(255)                             NOT NULL,
    constructor_id  INTEGER                                  NOT NULL,
    CONSTRAINT pk_driver PRIMARY KEY (id)
);

CREATE TABLE event
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grand_prix_id INTEGER                                  NOT NULL,
    label         VARCHAR(255)                             NOT NULL,
    start_at      TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    type          SMALLINT                                 NOT NULL,
    is_calculated BOOLEAN DEFAULT FALSE                    NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE event_result
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    driver_id         INTEGER                                 NOT NULL,
    event_id          INTEGER                                 NOT NULL,
    start_position    INTEGER,
    end_position      INTEGER                                 NOT NULL,
    dnf               BOOLEAN                                 NOT NULL,
    fastest_lap       BOOLEAN DEFAULT FALSE                   NOT NULL,
    driver_of_the_day BOOLEAN DEFAULT FALSE                   NOT NULL,
    nb_overtakes      INTEGER DEFAULT 0                       NOT NULL,
    CONSTRAINT pk_event_result PRIMARY KEY (id)
);

CREATE TABLE fantasy_score
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id       INTEGER                                 NOT NULL,
    driver_id      INTEGER,
    constructor_id INTEGER,
    points         INTEGER                                 NOT NULL,
    CONSTRAINT pk_fantasy_score PRIMARY KEY (id)
);

CREATE TABLE fantasy_team
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID                                    NOT NULL,
    label   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_fantasy_team PRIMARY KEY (id)
);

CREATE TABLE fantasy_team_composition
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grand_prix_id   INTEGER,
    fantasy_team_id BIGINT,
    CONSTRAINT pk_fantasy_team_composition PRIMARY KEY (id)
);

CREATE TABLE fantasy_team_composition_constructors
(
    constructor_id              INTEGER NOT NULL,
    fantasy_team_composition_id BIGINT  NOT NULL,
    CONSTRAINT pk_fantasy_team_composition_constructors PRIMARY KEY (constructor_id, fantasy_team_composition_id)
);

CREATE TABLE fantasy_team_composition_drivers
(
    driver_id                   INTEGER NOT NULL,
    fantasy_team_composition_id BIGINT  NOT NULL,
    CONSTRAINT pk_fantasy_team_composition_drivers PRIMARY KEY (driver_id, fantasy_team_composition_id)
);

CREATE TABLE fantasy_team_constructors
(
    constructor_id  INTEGER NOT NULL,
    fantasy_team_id BIGINT  NOT NULL,
    CONSTRAINT pk_fantasy_team_constructors PRIMARY KEY (constructor_id, fantasy_team_id)
);

CREATE TABLE fantasy_team_drivers
(
    driver_id       INTEGER NOT NULL,
    fantasy_team_id BIGINT  NOT NULL,
    CONSTRAINT pk_fantasy_team_drivers PRIMARY KEY (driver_id, fantasy_team_id)
);

CREATE TABLE grand_prix
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label    VARCHAR(255)                             NOT NULL,
    start_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    end_at   TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_grand_prix PRIMARY KEY (id)
);

CREATE TABLE market_value
(
    id             UUID   NOT NULL,
    driver_id      INTEGER,
    constructor_id INTEGER,
    value          BIGINT NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_market_value PRIMARY KEY (id)
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_username UNIQUE (username);

ALTER TABLE constructor
    ADD CONSTRAINT uc_constructor_name UNIQUE (name);

ALTER TABLE driver
    ADD CONSTRAINT FK_DRIVER_ON_CONSTRUCTOR FOREIGN KEY (constructor_id) REFERENCES constructor (id);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_GRAND_PRIX FOREIGN KEY (grand_prix_id) REFERENCES grand_prix (id);

ALTER TABLE event_result
    ADD CONSTRAINT FK_EVENT_RESULT_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES driver (id);

ALTER TABLE event_result
    ADD CONSTRAINT FK_EVENT_RESULT_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE fantasy_score
    ADD CONSTRAINT FK_FANTASY_SCORE_ON_CONSTRUCTOR FOREIGN KEY (constructor_id) REFERENCES constructor (id);

ALTER TABLE fantasy_score
    ADD CONSTRAINT FK_FANTASY_SCORE_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES driver (id);

ALTER TABLE fantasy_score
    ADD CONSTRAINT FK_FANTASY_SCORE_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE fantasy_team_composition
    ADD CONSTRAINT FK_FANTASY_TEAM_COMPOSITION_ON_FANTASY_TEAM FOREIGN KEY (fantasy_team_id) REFERENCES fantasy_team (id);

ALTER TABLE fantasy_team_composition
    ADD CONSTRAINT FK_FANTASY_TEAM_COMPOSITION_ON_GRAND_PRIX FOREIGN KEY (grand_prix_id) REFERENCES grand_prix (id);

ALTER TABLE fantasy_team
    ADD CONSTRAINT FK_FANTASY_TEAM_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE market_value
    ADD CONSTRAINT FK_MARKET_VALUE_ON_CONSTRUCTOR FOREIGN KEY (constructor_id) REFERENCES constructor (id);

ALTER TABLE market_value
    ADD CONSTRAINT FK_MARKET_VALUE_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES driver (id);

ALTER TABLE fantasy_team_composition_constructors
    ADD CONSTRAINT fk_fanteacomcon_on_constructor FOREIGN KEY (constructor_id) REFERENCES constructor (id);

ALTER TABLE fantasy_team_composition_constructors
    ADD CONSTRAINT fk_fanteacomcon_on_fantasy_team_composition FOREIGN KEY (fantasy_team_composition_id) REFERENCES fantasy_team_composition (id);

ALTER TABLE fantasy_team_composition_drivers
    ADD CONSTRAINT fk_fanteacomdri_on_driver FOREIGN KEY (driver_id) REFERENCES driver (id);

ALTER TABLE fantasy_team_composition_drivers
    ADD CONSTRAINT fk_fanteacomdri_on_fantasy_team_composition FOREIGN KEY (fantasy_team_composition_id) REFERENCES fantasy_team_composition (id);

ALTER TABLE fantasy_team_constructors
    ADD CONSTRAINT fk_fanteacon_on_constructor FOREIGN KEY (constructor_id) REFERENCES constructor (id);

ALTER TABLE fantasy_team_constructors
    ADD CONSTRAINT fk_fanteacon_on_fantasy_team FOREIGN KEY (fantasy_team_id) REFERENCES fantasy_team (id);

ALTER TABLE fantasy_team_drivers
    ADD CONSTRAINT fk_fanteadri_on_driver FOREIGN KEY (driver_id) REFERENCES driver (id);

ALTER TABLE fantasy_team_drivers
    ADD CONSTRAINT fk_fanteadri_on_fantasy_team FOREIGN KEY (fantasy_team_id) REFERENCES fantasy_team (id);