CREATE TABLE app_user
(
    id         UUID                        NOT NULL,
    username   VARCHAR(255)                NOT NULL,
    enabled    BOOLEAN                     NOT NULL,
    password   VARCHAR(255)                NOT NULL,
    role       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE constructor
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label     VARCHAR(255)                             NOT NULL,
    logo      VARCHAR(255),
    full_logo VARCHAR(255),
    CONSTRAINT pk_constructor PRIMARY KEY (id)
);

CREATE TABLE driver
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(255)                             NOT NULL,
    last_name       VARCHAR(255)                             NOT NULL,
    profile_picture VARCHAR(255)                             NOT NULL,
    team_id         INTEGER                                  NOT NULL,
    CONSTRAINT pk_driver PRIMARY KEY (id)
);

CREATE TABLE event
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grand_prix_id INTEGER                                  NOT NULL,
    label         VARCHAR(255)                             NOT NULL,
    start_at      TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    type          SMALLINT                                 NOT NULL,
    is_calculated BOOLEAN DEFAULT FALSE                    NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE event_result
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    driver_id         INTEGER                                 NOT NULL,
    race_id           INTEGER                                 NOT NULL,
    start_position    INTEGER,
    end_position      INTEGER                                 NOT NULL,
    dnf               BOOLEAN                                 NOT NULL,
    fastest_lap       BOOLEAN DEFAULT FALSE                   NOT NULL,
    driver_of_the_day BOOLEAN DEFAULT FALSE                   NOT NULL,
    nb_overtakes      INTEGER DEFAULT 0                       NOT NULL,
    CONSTRAINT pk_event_result PRIMARY KEY (id)
);

CREATE TABLE fantasy_score
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    race_id   INTEGER                                 NOT NULL,
    driver_id INTEGER,
    team_id   INTEGER,
    point     INTEGER                                 NOT NULL,
    CONSTRAINT pk_fantasy_score PRIMARY KEY (id)
);

CREATE TABLE fantasy_team
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID                                    NOT NULL,
    label   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_fantasy_team PRIMARY KEY (id)
);

CREATE TABLE fantasy_team_composition
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grand_prix_id INTEGER,
    user_team_id  BIGINT,
    CONSTRAINT pk_fantasy_team_composition PRIMARY KEY (id)
);

CREATE TABLE grand_prix
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label    VARCHAR(255)                             NOT NULL,
    start_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    end_at   TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_grand_prix PRIMARY KEY (id)
);

CREATE TABLE market_value
(
    id         UUID                        NOT NULL,
    driver_id  INTEGER,
    team_id    INTEGER,
    price      BIGINT                      NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_market_value PRIMARY KEY (id)
);

CREATE TABLE user_team_composition_drivers
(
    drivers_id               INTEGER NOT NULL,
    user_team_composition_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_team_composition_drivers PRIMARY KEY (drivers_id, user_team_composition_id)
);

CREATE TABLE user_team_composition_teams
(
    teams_id                 INTEGER NOT NULL,
    user_team_composition_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_team_composition_teams PRIMARY KEY (teams_id, user_team_composition_id)
);

CREATE TABLE user_team_drivers
(
    driver_id    INTEGER NOT NULL,
    user_team_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_team_drivers PRIMARY KEY (driver_id, user_team_id)
);

CREATE TABLE user_team_teams
(
    teams_id     INTEGER NOT NULL,
    user_team_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_team_teams PRIMARY KEY (teams_id, user_team_id)
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_username UNIQUE (username);

ALTER TABLE constructor
    ADD CONSTRAINT uc_constructor_label UNIQUE (label);

ALTER TABLE driver
    ADD CONSTRAINT FK_DRIVER_ON_TEAM FOREIGN KEY (team_id) REFERENCES constructor (id);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_GRAND_PRIX FOREIGN KEY (grand_prix_id) REFERENCES grand_prix (id);

ALTER TABLE event_result
    ADD CONSTRAINT FK_EVENT_RESULT_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES driver (id);

ALTER TABLE event_result
    ADD CONSTRAINT FK_EVENT_RESULT_ON_RACE FOREIGN KEY (race_id) REFERENCES event (id);

ALTER TABLE fantasy_score
    ADD CONSTRAINT FK_FANTASY_SCORE_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES driver (id);

ALTER TABLE fantasy_score
    ADD CONSTRAINT FK_FANTASY_SCORE_ON_RACE FOREIGN KEY (race_id) REFERENCES event (id);

ALTER TABLE fantasy_score
    ADD CONSTRAINT FK_FANTASY_SCORE_ON_TEAM FOREIGN KEY (team_id) REFERENCES constructor (id);

ALTER TABLE fantasy_team_composition
    ADD CONSTRAINT FK_FANTASY_TEAM_COMPOSITION_ON_GRAND_PRIX FOREIGN KEY (grand_prix_id) REFERENCES grand_prix (id);

ALTER TABLE fantasy_team_composition
    ADD CONSTRAINT FK_FANTASY_TEAM_COMPOSITION_ON_USER_TEAM FOREIGN KEY (user_team_id) REFERENCES fantasy_team (id);

ALTER TABLE fantasy_team
    ADD CONSTRAINT FK_FANTASY_TEAM_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE market_value
    ADD CONSTRAINT FK_MARKET_VALUE_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES driver (id);

ALTER TABLE market_value
    ADD CONSTRAINT FK_MARKET_VALUE_ON_TEAM FOREIGN KEY (team_id) REFERENCES constructor (id);

ALTER TABLE user_team_composition_drivers
    ADD CONSTRAINT fk_useteacomdri_on_driver FOREIGN KEY (drivers_id) REFERENCES driver (id);

ALTER TABLE user_team_composition_drivers
    ADD CONSTRAINT fk_useteacomdri_on_fantasy_team_composition FOREIGN KEY (user_team_composition_id) REFERENCES fantasy_team_composition (id);

ALTER TABLE user_team_composition_teams
    ADD CONSTRAINT fk_useteacomtea_on_constructor FOREIGN KEY (teams_id) REFERENCES constructor (id);

ALTER TABLE user_team_composition_teams
    ADD CONSTRAINT fk_useteacomtea_on_fantasy_team_composition FOREIGN KEY (user_team_composition_id) REFERENCES fantasy_team_composition (id);

ALTER TABLE user_team_drivers
    ADD CONSTRAINT fk_useteadri_on_driver FOREIGN KEY (driver_id) REFERENCES driver (id);

ALTER TABLE user_team_drivers
    ADD CONSTRAINT fk_useteadri_on_fantasy_team FOREIGN KEY (user_team_id) REFERENCES fantasy_team (id);

ALTER TABLE user_team_teams
    ADD CONSTRAINT fk_useteatea_on_constructor FOREIGN KEY (teams_id) REFERENCES constructor (id);

ALTER TABLE user_team_teams
    ADD CONSTRAINT fk_useteatea_on_fantasy_team FOREIGN KEY (user_team_id) REFERENCES fantasy_team (id);