CREATE TABLE price
(
    id         UUID   NOT NULL,
    driver_id  INTEGER,
    team_id    INTEGER,
    price      BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_price PRIMARY KEY (id)
);

ALTER TABLE price
    ADD CONSTRAINT FK_PRICE_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES driver (id);

ALTER TABLE price
    ADD CONSTRAINT FK_PRICE_ON_TEAM FOREIGN KEY (team_id) REFERENCES team (id);